owner: paulreimer
repo: up.p-rimes.net

sites: []

status-website:
  cname: up.p-rimes.net
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Monitored Endpoints"
  introTitle: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
